"""
plot_mimo_ofdm_ber.py
---------------------
Plot BER curves for 2×2 MIMO-OFDM over a 3GPP TDL fading channel.

This script reads the BER results generated by `mimo_ofdm_ber.c`
and outputs publication-quality BER graphs.

Input:
    results/mimo_ofdm_ber_data.csv

Output:
    images/mimo_ofdm_ber_graph.png
    images/mimo_ofdm_ber_graph.svg

CSV format example:
    SNR_dB, BER_BPSK, BER_QPSK, BER_16QAM, BER_64QAM, BER_256QAM

Features:
    - Supports all modulations tested in the simulator (BPSK–256QAM)
    - Automatically detects available BER columns
    - Plots in log-scale (semilogy) using Matplotlib
    - Paper-style formatting (Times New Roman, STIX math)
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import sys

# =============================================================================
#  Setup
# =============================================================================

CSV_PATH = "results/mimo_ofdm_ber_data.csv"
OUTPUT_DIR = "images"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Matplotlib appearance (paper-like)
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams["mathtext.fontset"] = "stix"
plt.rcParams["font.size"] = 14

# =============================================================================
#  Load CSV
# =============================================================================
if not os.path.exists(CSV_PATH):
    print(f"[ERROR] CSV file not found: {CSV_PATH}")
    sys.exit(1)

df = pd.read_csv(CSV_PATH)

# Extract SNR
SNR = df["SNR_dB"]

# Detect modulation columns automatically
mod_cols = [c for c in df.columns if c.startswith("BER_") and c != "SNR_dB"]

# Preferred modulation order
preferred_order = ["BER_BPSK", "BER_QPSK", "BER_16QAM", "BER_64QAM", "BER_256QAM"]
mod_cols = [c for c in preferred_order if c in mod_cols]

# Labels for plotting
labels = {
    "BER_BPSK": "BPSK (1 bit/sym)",
    "BER_QPSK": "QPSK (2 bit/sym)",
    "BER_16QAM": "16-QAM (4 bit/sym)",
    "BER_64QAM": "64-QAM (6 bit/sym)",
    "BER_256QAM": "256-QAM (8 bit/sym)",
}

markers = ["o", "s", "^", "v", "D"]

# =============================================================================
#  Plot
# =============================================================================

plt.figure(figsize=(8, 6))

for col, marker in zip(mod_cols, markers):
    plt.semilogy(
        SNR,
        df[col],
        marker=marker,
        markersize=8,
        markerfacecolor="none",
        linewidth=2.5,
        label=labels.get(col, col),
    )

# Axis settings
plt.ylim(1e-5, 1)
plt.xlabel("SNR [dB]", fontsize=18)
plt.ylabel("Bit Error Rate (BER)", fontsize=18)

plt.grid(True, which="both", linestyle="--", linewidth=0.6, alpha=0.6)
plt.legend(fontsize=13, loc="upper right", frameon=True, edgecolor="black")

plt.title("MIMO-OFDM BER over 3GPP TDL Channel", fontsize=17)
plt.tight_layout()

# Save images
out_png = os.path.join(OUTPUT_DIR, "mimo_ofdm_ber_graph.png")
out_svg = os.path.join(OUTPUT_DIR, "mimo_ofdm_ber_graph.svg")

plt.savefig(out_png, dpi=300)
plt.savefig(out_svg, dpi=300)

print(f"[OK] Saved: {out_png}")
print(f"[OK] Saved: {out_svg}")

plt.show()
